artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/Data_ingestion
  local_data_file: artifacts/Data_ingestion/dataset.zip
  unzip_dir: artifacts/Data_ingestion




data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.jsonl", "test.jsonl", "validation.jsonl"]



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/Data_ingestion/dataset
  tokenizer_name: t5-small



model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/dataset
  model_ckpt: t5-small




model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv


